
const foodData = [
    { name: "김치볶음밥", ingredients: ["돼지고기","밥", "김치", "앞다리살"], img: "https://raw.githubusercontent.com/JANCOOKWebProject/Web-Programming-Projectt/main/food-image/kimchi-rice.jpg", link: "recipe.html" },
    { name: "된장찌개", ingredients: ["된장", "두부", "채소류"], img: "https://raw.githubusercontent.com/JANCOOKWebProject/Web-Programming-Projectt/main/food-image/soybean-soup.jpg", link: "recipe.html" },
            { name: "스테이크", ingredients: ["소고기","등심", "안심"], img: "https://raw.githubusercontent.com/JANCOOKWebProject/Web-Programming-Projectt/main/food-image/steak.jpg", link: "recipe.html" },
    { name: "스테이크", ingredients: ["소고기","등심", "안심"], img: "https://raw.githubusercontent.com/JANCOOKWebProject/Web-Programming-Projectt/main/food-image/steak.jpg", link: "recipe.html" },
    { name: "호박버섯 볶음", ingredients: ["호박", "버섯"], img: "https://raw.githubusercontent.com/JANCOOKWebProject/Web-Programming-Projectt/main/food-image/sauteed-mushrooms-with-pumpkin-sweet-pepper.jpg", link: "recipe.html" },
    { name: "제육볶음", ingredients: ["목살", "고추장", "양파", "마늘", "간장"], img: "https://raw.githubusercontent.com/JANCOOKWebProject/Web-Programming-Projectt/main/food-image/pepper-paste-fork.jpg", link: "recipe.html" },
    { name: "계란찜", ingredients: ["계란", "소금", "대파"], img: "https://raw.githubusercontent.com/JANCOOKWebProject/Web-Programming-Projectt/main/food-image/hangug-eumsig-gyelan-jjim-ttoneun-bansug-gyelan.jpg", link: "recipe.html" },
    { name: "떡볶이", ingredients: ["떡", "고추장", "어묵", "대파"], img: "https://raw.githubusercontent.com/JANCOOKWebProject/Web-Programming-Projectt/main/food-image/beullaeg-bodeu-baegyeong-e-chijeu-tokbokki-hangug-jeontong-eumsig-jeomsim-yoli.jpg", link: "recipe.html" },
    { name: "계란말이", ingredients: ["계란", "당근", "양파", "소금"], img: "https://raw.githubusercontent.com/JANCOOKWebProject/Web-Programming-Projectt/main/food-image/egg-cake.png", link: "recipe.html" },
    { name: "토마토 파스타", ingredients: ["스파게티면", "토마토소스", "마늘", "양파", "치즈"], img: "https://raw.githubusercontent.com/JANCOOKWebProject/Web-Programming-Projectt/main/food-image/tasty-appetizing-classic-italian-spaghetti-pasta-with-tomato-sauce-cheese-parmesan-basil-plate-ingredients-cooking-pasta-white-marble-table.jpg", link: "recipe.html" },
    { name: "돼지고기 볶음 스파게티", ingredients: ["앞다리살", "스파게티면", "양파", "간장", "고추기름"], img: "https://raw.githubusercontent.com/JANCOOKWebProject/Web-Programming-Projectt/main/food-image/stir-fry-spaghetti-put-pork-bowl.jpg", link: "recipe.html" },
    { name: "참치마요덮밥", ingredients: ["밥", "참치캔", "마요네즈", "간장", "김"], img: "https://raw.githubusercontent.com/JANCOOKWebProject/Web-Programming-Projectt/main/food-image/mas-issneun-chamchi-lesipi.jpg", link: "recipe.html" },
    { name: "해물파전", ingredients: ["부침가루", "오징어", "새우", "대파", "계란"], img: "https://raw.githubusercontent.com/JANCOOKWebProject/Web-Programming-Projectt/main/food-image/seafood-pancake.png", link: "recipe.html" },
    { name: "김치찌개", ingredients: ["김치", "두부", "목살", "앞다리살", "대파"], img: "https://raw.githubusercontent.com/JANCOOKWebProject/Web-Programming-Projectt/main/food-image/kimchi-stew.jpeg", link: "recipe.html" },
    { name: "오징어 볶음", ingredients: ["오징어", "고추장", "양파", "당근"], img: "https://raw.githubusercontent.com/JANCOOKWebProject/Web-Programming-Projectt/main/food-image/stir-fried-squid.png", link: "recipe.html" },
    { name: "버섯 리조또", ingredients: ["밥", "버섯", "양파", "치킨스톡"], img: "https://raw.githubusercontent.com/JANCOOKWebProject/Web-Programming-Projectt/main/food-image/mushroom-risotto.png", link: "recipe.html" },
    { name: "해물짬뽕", ingredients: ["면", "해물", "고추기름", "양파"], img: "https://raw.githubusercontent.com/JANCOOKWebProject/Web-Programming-Projectt/main/food-image/seafood-jjamppong.png", link: "recipe.html" },
    { name: "닭갈비", ingredients: ["닭다리살", "고추장", "양배추", "당근"], img: "https://raw.githubusercontent.com/JANCOOKWebProject/Web-Programming-Projectt/main/food-image/spicy-chicken-stew.png", link: "recipe.html" },
    { name: "부대찌개", ingredients: ["햄", "소세지", "두부", "김치"], img: "https://raw.githubusercontent.com/JANCOOKWebProject/Web-Programming-Projectt/main/food-image/army-stew.png", link: "recipe.html" },
    { name: "잡채", ingredients: ["당면", "소고기", "당근", "버섯"], img: "https://raw.githubusercontent.com/JANCOOKWebProject/Web-Programming-Projectt/main/food-image/japchae.png", link: "recipe.html" },
    { name: "미역국", ingredients: ["미역", "소고기", "간장"], img: "https://raw.githubusercontent.com/JANCOOKWebProject/Web-Programming-Projectt/main/food-image/seaweed-soup.png", link: "recipe.html" },
    { name: "토마토달걀볶음", ingredients: ["토마토", "계란", "소금"], img: "https://raw.githubusercontent.com/JANCOOKWebProject/Web-Programming-Projectt/main/food-image/tomato-egg.png", link: "recipe.html" },
];